= MIRISim TSO: Post-Treatment of MIRISim Images for Time-Series Observations
:author: Marine Martin-Lagarde & Christophe Cossou
:sectnums:
:toc: left
:toclevels: 4
:source-language: python
:experimental:
:xrefstyle: short


== Getting Started
IMPORTANT: Current version is still under development.

MRISim_TSO is a Python 3 package. As MIRISim has not been designed for Time-Series Observations (TSO), in order to create those, one has to start a new simulations at each time step. This implies getting rig of all the systematic noises and drifts. The present package aims at reintroducing the detector systematics in the files resulting of a MIRISim computation.

The package have been designed exclusively to treat MIRISim output files, hence we try to be up to date on the data model. Please make sure you comply to the format and folder arborescence.

[WARNING]
====
MIRISim simulations *MUST* be done without poisson noise, latency and Cosmic rays. See <<limitations>> for more informations.
====

Here, we create new files in the MIRISim result folder containing a new `det_image` accounting for instrumental systematics.

These Instructions will get you to have a version of the package on your computer up and running. Note that a complete and detailed user manual is available in the documentation. It contains some important usage rules, and we strongly advise a careful reading before using this treatment.

Every step described hereafter have to be done in the directory containing the `setup.py` file (usually, the downloaded folder).

=== Requirements
The package is developed in `Python 3.6`. The required python libraries are specified in the file 'requirements.txt'. To ensure all dependencies are satisfied, run the following command line:
[source, bash]
----
pip install -r requirements.txt
----
or in anaconda
[source, bash]
----
conda install --file requirements.txt
----

=== Installation
You can install mirisim_tso as a standard Python module. To do that, in the root directory of the package, do:
[source, bash]
----
python setup.py install
----
In your python script or in a python environment, import the module with:
[source]
----
import mirisim_tso
----

For developers, create a symbolic link so that each time the code is changed, the imported module is changed accordingly (still in the root directory):
[source, bash]
----
pip install -e .
----

Beware, there is a compressed FITS file, MIRI_FM_MIRIMAGE_MASK_07.02.01.fits.gz, in the git,
https://gitlab.com/mmartin-lagarde/mirisim_tso/-/tree/master/mirisim_tso/data
This contains the mask, which is used for not computing the Poisson noise on the pixels which are flagged bad.
(trying to compute the Poisson distribution of a negative parameter crashes the system) 

== Configuration
This section describe all parameters available in the configuration file for mirisim_tso.
Each subsection represent a section of the .ini file

=== simulations
[source, ini]
----
[simulations]
dir = "/Users/gastaud/test_dap/cascade/simulation_LRS/"
filtername = "simulation_*"
overwrite = True
----
The program shall process the folders (dir, filtername), in our example
/Users/gastaud/test_dap/cascade/simulation_LRS/simulation_000 to
/Users/gastaud/test_dap/cascade/simulation_LRS/simulation_999 .

[cols="<,<,<",options="header",]
|=======================================================================
|Parameter |Type / Unit | Description
|input_dir | str | Folder name. All folders found in this folder and whose name begins with filtername will be assumed to be MIRISim simulations
|filtername | str | filter the folders in dir
|time_filename | str | name of the file containing index, phase and time for each integration, default is input_dir+times.dat
|overwrite | bool | Existing level 1B files are *NOT* overwriting, even with `overwrite=True`.
However, for each combination of effect, a specific file is created.
This file will be overwritten if this parameter is *True*
|=======================================================================


=== response_drift
Add *response drift systematic*, i.e the fact that the detector takes time to settle in a stable configuration at the start of the observation
and first integrations will be different than the rest of integrations for the observations.

[source, ini]
----
[response_drift]
active = true
----

[cols="<,<,<",options="header",]
|=======================================================================
|Parameter |Type / Unit | Description
|active | bool | Activate Response Drift
|=======================================================================


=== response_drift_one
Same systematics than before, just the comput is different, using only one exponential.

[source, ini]
----
[response_drift_one]
active = true
----

[cols="<,<,<",options="header",]
|=======================================================================
|Parameter |Type / Unit | Description
|active | bool | Activate Response Drift One
|=======================================================================

=== idle_recovery
Add *systematic* related to *Idle time* (the time before the observation where
a reset is done every frame (during pointing for instance).

[source, ini]
----
[idle_recovery]
active = true
duration = 1000.
----

[cols="<,<,<",options="header",]
|=======================================================================
|Parameter |Type / Unit | Description
|active | bool | Activate Idle Recovery
| duration | float / seconds | Idle time before observation starts
|=======================================================================

=== anneal_recovery
Add *systematic* related to an *Anneal*.

[source, ini]
----
[anneal_recovery]
active = true
time = 600.
----

[cols="<,<,<",options="header",]
|=======================================================================
|Parameter |Type / Unit | Description
|active | bool | Activate Anneal Recovery
| duration | float / seconds | Time ellapsed since last anneal, before Observation starts. 0 means the anneal was done, then observation starts right after. 600 (*default*) means there was 10 minutes between end of anneal and start of observation
|=======================================================================

=== noise
Add Poisson noise to the observation
(this needs to be done here because we can't add systematics properly if poisson noise was processed in MIRISim).

[source, ini]
----
[noise]
active  = true
----

[cols="<,<,<",options="header",]
|=======================================================================
|Parameter |Type / Unit | Description
|active | bool | Activate poisson noise
|=======================================================================

=== noise
Add Poisson noise to the observation.
It is done with a different algorithm than the precedent, see annex.
This keyword can be omitted from the ini file.



=== background
Add background to the observation.
Background is an image in electron per second of the background flux, in a FITS file.
The image can be in an extension sci or just a straightforward FITS.
This keyword can be omitted from the ini file.

[source, ini]
----
[background]
filename  = None
----


[cols="<,<,<",options="header",]
|=======================================================================
|Parameter |Type / Unit | Description
|filename | str | Add Background
|=======================================================================


=== orbit
Add obs-date, obs-time and obs-mjd to the observation.
For this we give the epoch (ephemeris) in BarycenterJulian Day of the transit, and the period of the exoplanet in day.

[source, ini]
----
[orbit]
epoch  = 0.
period = 0.
----


[cols="<,<,<",options="header",]
|=======================================================================
|Parameter |Type / Unit | Description
|epoch | float/Julian Day | ephemeris of the transit
|period | float/day | period of the exo-planet
|=======================================================================


== How to use
In Python, you have 2 solutions. Either run for a single simulation, or a serie of observations.

[[limitations]]
=== Limitations

.This package is intended to work only for MIRISim simulations that check the following conditions:
* Poisson noise deactivated
* latency deactivated
* cosmic rays deactivated
* *LRS_SLITLESS* observation

To deactivate the required effects in MIRISim, in Python you must do:
[source]
----
simulator_config = SimulatorConfig.makeSimulator(
take_webbPsf=False,
include_refpix=True,
include_poisson=False,
include_readnoise=True,
include_badpix=True,
include_dark=True,
include_flat=True,
include_gain=True,
include_nonlinearity=True,
include_drifts=True,
include_latency=False,
cosmic_ray_mode='NONE') # SOLAR_MIN, SOLAR_MAX, SOLAR_FLARE, NONE
----
If you use the command-line tool, the corresponding simulator.ini file is:
[source, ini]
----
[SCASim]
  include_refpix = T                    # Include reference pixels in data.
  include_poisson = F                   # Apply poisson noise.
  include_readnoise = T                 # Apply read noise noise.
  include_badpix = T                    # Apply bad pixels.
  include_dark = T                      # Apply dark current / hot pixels.
  include_flat = T                      # Apply flat field.
  include_gain = T                      # Apply gain.
  include_nonlinearity = T              # Apply non-linearity.
  include_drifts = T                    # Include detector drifts.
  include_latency = F                   # Include detector latency.
  cosmic_ray_mode = NONE           # Cosmic ray environment mode.
----

=== Serie of observations
This is how the package is intended to be used.

[source]
----
import mirisim_tso

mirisim_tso.utils.init_log()

config_filename = "post_treatment.ini"
mirisim_tso.sequential_lightcurve_post_treatment(config_filename)
----

=== Single observation
[source]
----
import mirisim_tso

mirisim_tso.utils.init_log()

simulation_name = "my_simulation"
config_filename = "post_treatment.ini"
mirisim_tso.single_simulation_post_treatment(simulation_folder=simulation_name, conf=config_filename)
----

== Author
   - ***Marine Martin-Lagarde*** *(Corresponding author)* - CEA-Saclay - marine.martin-lagarde@cea.fr
   - ***Christophe Cossou*** - IAS-Orsay - *Python support and package architecture*

== Licence
**<center>Work in progress</center>**

== Acknowledgments
If you want to use this code in a scientific publication, it would be appreciated if you cite us. *No referenced article yet*   
The author is partly funded by a CNES grant. The research leading to these development has received funding from the European Union’s Horizon 2020 Research and Innovation Programme, under Grant Agreement 776403.
**<center>Work in progress</center>**

== References
The reference articles for the calculations used in the code are the following :   
- D.Dicken et al. _in prep_

== Annex A
The directory misc contains routines and scripts for the developpers (sandbox).

== Annex B (programmers only)
To add an effect, you have to modify the following 6 files :
[horizontal]
   README.adoc:: the present document, do not forget to document !
   version.py:: and no not forget to update the version !
   effects.py:: here we put the new function
   main.py:: here we add the lines to call the new function
   utils.py:: add the name of the new function in write_det_image_with_effects
   configspec.ini:: add the name of the new function

== Annex C (add noise)
check mirism_tso.effects.poisson_noise

SOLUTION = REWRITE ALGORITHM, WORKS !

Remark :
the input ramp has read noise, hook at the beginning ?, non-linearity but no Poisson noise, no cosmic rays .

First step :  check_mirisim_tso_poisson_noise.py
read the configuration,
read the mask file name and the det_images_filename  from the configuration,
read the mask and the original ramp (from det_images_filename)
call the mirisim_tso.effects.poisson_noise ==> new ramp
compute the slope of the original ramp (one image, DN/s)
compute the slope of the new ramp (one image, DN/s)
show the difference of images
plot the difference for the slice with maximum flux.
check_mirisim_tso_poisson_noise does not work.


Second Step : compute_noise_alamano.py
execute the function mirisim_tso.effects.poisson_noise  line by line to find a bug.
write the intermediate products in fits files
plot the results : plot_slopes.py
check_mirisim_tso_poisson_noise does work.


Third step : check_mirisim_tso_poisson_noise_with_perfect_ramp.py
check mirisim_tso.effects.poisson_noise with as input a generated perfect ramp.
This ramp is computed from a subarray with reference, dead pixel of the illumination model image.
check_mirisim_tso_poisson_noise does  work.


4th step : check_mirisim_tso_poisson_noise_with_perfect_ramp_offset.py
same than before, but I add to the synthetic ramp an offset image, with random values.
check_mirisim_tso_poisson_noise does  work.

5th step : compute_noise_correct.py
try another algorithm :

1) compute the consecutive difference of the ramp ==> cube of images DN/s
      duplicate the first difference
2) draw Poisson on the cube of differences
3) the trick :
    remove the original to the noisy images to get only the noise !
4) integrate the noise only,
5) add the integrated noise only to the original ramp
This works


== Annex D (merge files)
The output of MAST will be files of 2 GigaBytes.
The program merge_sim_files.py in the directory misc regroup the small input files in big files, keeping the headers.

